# Generated by Django 2.1.8 on 2019-05-13 10:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('street_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('suburb', models.CharField(blank=True, db_index=True, max_length=200)),
                ('postcode', models.CharField(blank=True, db_index=True, max_length=200)),
                ('state', models.CharField(blank=True, db_index=True, max_length=200)),
                ('contact_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
